//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inferno.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChaosModeLocalize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChaosModeLocalize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inferno.Properties.ChaosModeLocalize", typeof(ChaosModeLocalize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the player&apos;s targetability.
        ///If OFF, the player will be targeted depending on the position relationship with the ped..
        /// </summary>
        internal static string AttackPlayerCorrection {
            get {
                return ResourceManager.GetString("AttackPlayerCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of player being targeted..
        /// </summary>
        internal static string AttackPlayerCorrectionProbability {
            get {
                return ResourceManager.GetString("AttackPlayerCorrectionProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedestrians near the player become armed and attacking..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChaosMode( Riot Mode).
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of explosive weapons being forcibly selected..
        /// </summary>
        internal static string ForceExplosiveWeaponProbability {
            get {
                return ResourceManager.GetString("ForceExplosiveWeaponProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether it affects mission-related characters.
        /// -AffectAllCharacter: Include all mission-related characters.
        /// -ExcludeUniqueCharacter: Exclude named characters and important mission characters.
        /// -ExcludeAllMissionCharacter: Exclude all mission-related characters..
        /// </summary>
        internal static string MissionCharacterBehaviour {
            get {
                return ResourceManager.GetString("MissionCharacterBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override mission character&apos;s weapons.
        ///Works independently of &apos;MissionCharacterBehaviour&apos; settings..
        /// </summary>
        internal static string OverrideMissionCharacterWeapon {
            get {
                return ResourceManager.GetString("OverrideMissionCharacterWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius of rioting..
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy of ped&apos;s attack..
        /// </summary>
        internal static string ShootAccuracy {
            get {
                return ResourceManager.GetString("ShootAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of peds firing a gun without regard to whether the line of fire is through or not..
        /// </summary>
        internal static string StupidShootingRate {
            get {
                return ResourceManager.GetString("StupidShootingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of peds changing weapon..
        /// </summary>
        internal static string WeaponChangeProbability {
            get {
                return ResourceManager.GetString("WeaponChangeProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of peds dropping weapon..
        /// </summary>
        internal static string WeaponDropProbability {
            get {
                return ResourceManager.GetString("WeaponDropProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited to melee weapons..
        /// </summary>
        internal static string Yakyu {
            get {
                return ResourceManager.GetString("Yakyu", resourceCulture);
            }
        }
    }
}
