//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inferno.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntitiesLocalize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitiesLocalize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inferno.Properties.EntitiesLocalize", typeof(EntitiesLocalize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicles in which the citizen rides suddenly accelerate..
        /// </summary>
        internal static string CitizenNitroDescription {
            get {
                return ResourceManager.GetString("CitizenNitroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check frequency..
        /// </summary>
        internal static string CitizenNitroInterval {
            get {
                return ResourceManager.GetString("CitizenNitroInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of triggering..
        /// </summary>
        internal static string CitizenNitroProbability {
            get {
                return ResourceManager.GetString("CitizenNitroProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of effects..
        /// </summary>
        internal static string CitizenNitroRange {
            get {
                return ResourceManager.GetString("CitizenNitroRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocket acceleration (Around vehicles).
        /// </summary>
        internal static string CitizenNitroTitle {
            get {
                return ResourceManager.GetString("CitizenNitroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles in and around the area where the driver is riding will go on fire..
        /// </summary>
        internal static string CitizenVehicleBombDescription {
            get {
                return ResourceManager.GetString("CitizenVehicleBombDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check frequency..
        /// </summary>
        internal static string CitizenVehicleBombInterval {
            get {
                return ResourceManager.GetString("CitizenVehicleBombInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of triggering..
        /// </summary>
        internal static string CitizenVehicleBombProbability {
            get {
                return ResourceManager.GetString("CitizenVehicleBombProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of effects..
        /// </summary>
        internal static string CitizenVehicleBombRange {
            get {
                return ResourceManager.GetString("CitizenVehicleBombRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle bombing..
        /// </summary>
        internal static string CitizenVehicleBombTitle {
            get {
                return ResourceManager.GetString("CitizenVehicleBombTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizens drive rougher..
        /// </summary>
        internal static string CrazyDrivingDescription {
            get {
                return ResourceManager.GetString("CrazyDrivingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rash driving.
        /// </summary>
        internal static string CrazyDrivingTitle {
            get {
                return ResourceManager.GetString("CrazyDrivingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute immediately.
        /// </summary>
        internal static string ForceRideAction {
            get {
                return ResourceManager.GetString("ForceRideAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a player repeatedly sounds the horn while driving, nearby citizens are forced to get into your car..
        /// </summary>
        internal static string ForceRideDescription {
            get {
                return ResourceManager.GetString("ForceRideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required number of hits..
        /// </summary>
        internal static string ForceRideInputCount {
            get {
                return ResourceManager.GetString("ForceRideInputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input grace period for repeated honking..
        /// </summary>
        internal static string ForceRideInputTimeout {
            get {
                return ResourceManager.GetString("ForceRideInputTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced entry.
        /// </summary>
        internal static string ForceRideTitle {
            get {
                return ResourceManager.GetString("ForceRideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizens paratroop down near the player..
        /// </summary>
        internal static string ParachuteDescription {
            get {
                return ResourceManager.GetString("ParachuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen generation interval..
        /// </summary>
        internal static string ParachuteIntterval {
            get {
                return ResourceManager.GetString("ParachuteIntterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airborne citizen force.
        /// </summary>
        internal static string ParachuteTitle {
            get {
                return ResourceManager.GetString("ParachuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizens rob vehicles in the vicinity..
        /// </summary>
        internal static string RobberDescription {
            get {
                return ResourceManager.GetString("RobberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check frequency..
        /// </summary>
        internal static string RobberInterval {
            get {
                return ResourceManager.GetString("RobberInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of triggering..
        /// </summary>
        internal static string RobberProbability {
            get {
                return ResourceManager.GetString("RobberProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of effects..
        /// </summary>
        internal static string RobberRange {
            get {
                return ResourceManager.GetString("RobberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen vehicle robbery.
        /// </summary>
        internal static string RobberTitle {
            get {
                return ResourceManager.GetString("RobberTitle", resourceCulture);
            }
        }
    }
}
