//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inferno.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerLocalize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerLocalize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inferno.Properties.PlayerLocalize", typeof(PlayerLocalize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a while of not having taken any damage, it gradually recovers its strength and armor to the maximum value..
        /// </summary>
        internal static string AutoHealDescription {
            get {
                return ResourceManager.GetString("AutoHealDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-recovery.
        /// </summary>
        internal static string AutoHealTitle {
            get {
                return ResourceManager.GetString("AutoHealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play background music during the activation of Trevor&apos;s ability.
        ///Play background music while Trevor&apos;s ability is activated.
        ///Place the BGM you wish to play as a wav file in “scripts/SpecialAbilityBgm”..
        /// </summary>
        internal static string BgmDescription {
            get {
                return ResourceManager.GetString("BgmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trevor Music.
        /// </summary>
        internal static string BgmTitle {
            get {
                return ResourceManager.GetString("BgmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneously pressing “Aim” and “Fire” while in the “ Unarmed” state will fire missiles from the vehicle..
        /// </summary>
        internal static string BondCarDescription {
            get {
                return ResourceManager.GetString("BondCarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool time..
        /// </summary>
        internal static string BondCardInterval {
            get {
                return ResourceManager.GetString("BondCardInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond car.
        /// </summary>
        internal static string BondCarTitle {
            get {
                return ResourceManager.GetString("BondCarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound effects when the player dies.
        ///Place the sound effects you wish to play as wav files in “scripts/Pichun”..
        /// </summary>
        internal static string DeathSfxDescription {
            get {
                return ResourceManager.GetString("DeathSfxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death sound effect.
        /// </summary>
        internal static string DeathSfxTitle {
            get {
                return ResourceManager.GetString("DeathSfxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting out of the car while honking the horn activates the emergency ejection..
        /// </summary>
        internal static string EmergencyEscapeDescription {
            get {
                return ResourceManager.GetString("EmergencyEscapeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejection power..
        /// </summary>
        internal static string EmergencyEscapePower {
            get {
                return ResourceManager.GetString("EmergencyEscapePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency escape.
        /// </summary>
        internal static string EmergencyEscapeTitle {
            get {
                return ResourceManager.GetString("EmergencyEscapeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding down jump and sprint at the same time causes the player to fluff up and jump up..
        /// </summary>
        internal static string FloatingDescription {
            get {
                return ResourceManager.GetString("FloatingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy Jump.
        /// </summary>
        internal static string FloatingTitle {
            get {
                return ResourceManager.GetString("FloatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string KillMeAction {
            get {
                return ResourceManager.GetString("KillMeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills the player..
        /// </summary>
        internal static string KillMeDescription {
            get {
                return ResourceManager.GetString("KillMeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicide.
        /// </summary>
        internal static string KillMeTitle {
            get {
                return ResourceManager.GetString("KillMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Wanted Level to 0..
        /// </summary>
        internal static string NoWantedAction {
            get {
                return ResourceManager.GetString("NoWantedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent wanted level from increasing..
        /// </summary>
        internal static string NoWantedDescription {
            get {
                return ResourceManager.GetString("NoWantedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Wanted level below this value..
        /// </summary>
        internal static string NoWantedLevel {
            get {
                return ResourceManager.GetString("NoWantedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress wanted level.
        /// </summary>
        internal static string NoWantedTitle {
            get {
                return ResourceManager.GetString("NoWantedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragdoll.
        /// </summary>
        internal static string RagdollAction {
            get {
                return ResourceManager.GetString("RagdollAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Duck&quot; + &quot;Jump&quot; will deactivate the player..
        /// </summary>
        internal static string RagdollDescription {
            get {
                return ResourceManager.GetString("RagdollDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players ragdoll.
        /// </summary>
        internal static string RagdollTitle {
            get {
                return ResourceManager.GetString("RagdollTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the player is resurrected after death or at the start of a mission, “Armor,” “ Health,” and “Special Ability Gauge” are all restored..
        /// </summary>
        internal static string SupplierDescription {
            get {
                return ResourceManager.GetString("SupplierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full recovery.
        /// </summary>
        internal static string SupplierTitle {
            get {
                return ResourceManager.GetString("SupplierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the vehicle&apos;s endurance value on the screen.
        ///
        ///Red: Fuel tank
        ///Blue: body of the vehicle
        ///Green: Engine
        ///Yellow: Time remaining before explosion.
        /// </summary>
        internal static string VehicleHUDDescription {
            get {
                return ResourceManager.GetString("VehicleHUDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s HUD.
        /// </summary>
        internal static string VehicleHUDTitle {
            get {
                return ResourceManager.GetString("VehicleHUDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport to.
        /// </summary>
        internal static string WarpAction {
            get {
                return ResourceManager.GetString("WarpAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleports the player to the location marked on the map. It is sometimes buried in the ground, but it is normal..
        /// </summary>
        internal static string WarpDescription {
            get {
                return ResourceManager.GetString("WarpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string WarpTitle {
            get {
                return ResourceManager.GetString("WarpTitle", resourceCulture);
            }
        }
    }
}
